export const types = {
    // FACTORING
    FACTORING_INIT: "FACTORING_INIT",
    FACTORING_LOAD_DTE: "FACTORING_LOAD_DTE",
    FACTORING_CHANGE_BLOCK_USUARIO: "FACTORING_CHANGE_BLOCK_USUARIO",
    FACTORING_RESET: "FACTORING_RESET",
}

